spring:
  application:
    name: gateway
  cloud:
    consul:
      host: xxx.xxx.xx.xxx
      discovery:
        #hostname:  这个配置是指当前服务所在的主机地址， 不配置则是默认本机的地址
        service-name: gateway
        heartbeat:
          enabled: true
        scheme: http
        acl-token: xxxxxxxxxxx
      scheme: http
    loadbalancer:
      ribbon:
        enabled: false
    gateway:
      discovery:
        locator:
          enabled: true  #开启服务发现
          lower-case-service-id: true # 设置发现的服务都是小写
          route-id-prefix: serv- #设定发现服务的默认前缀
          include-expression: false  #关掉服务发现后自动创建路由，因为这个自动创建的路由不支持在线更改，所以禁掉



  redis:
    password: 123456
server:
  port: 23457
management:
  endpoints:
    web:
      exposure:
        include: "*" #这个配置不应该开全部的，这里测试方便就全部开放，有很多敏感的接口, 实际上只需要开放 gateway 就可以了

